<a href="https://colab.research.google.com/github/Shadi-Aldbaiss/Python/blob/main/Python_Practical_Problem_solving_2_5_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **List**

In [132]:
#Q1: Print only even numbers from list
numberList=[1,2,3,4,5,6,7,8,9,10]
evenNumberList=[]
for n in numberList:
  if n % 2 == 0:
    evenNumberList.append(n)
print('Even Number List',evenNumberList)

#---------------------------------------------------------------------

#Q2:Function to return a list of common elements from toe lists
def getCommonElements(l1,l2):
  commonElements=[]
  commonElements=list1.intersection(list2)
  return commonElements

list1={1,2,3,4,5,6,7,8}
list2={5,6,7,8,9,10}
commonElement=getCommonElements(list1,list2)
print("Common Element",commonElement)

#-----------------------------------------------------------------------

#Q3: Reverse a list without using reverse() or slicing
my_list=[1,2,3,4,5,6,7,8,9,10]
reversedList=[]
for i in range(len(my_list)-1,-1,-1):
  reversedList.append(my_list[i])
print("Reversed List",reversedList)

#------------------------------------------------------------------------

#Q4: Calculat all elements of list withot using sum() function
my_list=[10,20,30,40,50,60,70,80,90,100]
sum=0
for n in my_list:
  sum=sum+n
print("The sum of the list elements = ",sum)

#-------------------------------------------------------------------------

#Q5 : Get the second largest number on the list
my_list=[10,30,50,80,90,20,100,40,60,70]
orderedList=sorted(my_list)
print("The second largest number on the list is = ",orderedList[-2])

# ------------------------------------------------------------------------



Even Number List [2, 4, 6, 8, 10]
Common Element {8, 5, 6, 7}
Reversed List [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
The sum of the list elements =  550
The second largest number on the list is =  90


# **Tuple**

In [133]:
#Q1 : Print maximum and minimum numbers without using max()and  min()
my_tuple = (10,30,50,20,40)
my_list = list(my_tuple)
my_list.sort()
my_tuple=tuple(my_list)
print("Maximum number = ",my_tuple[-1])
print("Minimum number = ",my_tuple[0])

#------------------------------------------------------------------------

#Q2: function to swap the first and last element of a tuple
def swap(myTuple):
  my_list=list(myTuple)
  temp=my_list[0]
  my_list[0]=my_list[-1]
  my_list[-1]=temp
  my_tuple=tuple(my_list)
  return my_tuple

my_tuple=(10,20,30,40,50)
swappedTuple=swap(my_tuple)
print("Swapped Tuple",swappedTuple)

#------------------------------------------------------------------------

#Q3:convert tuple to list and sort it
my_tuple=(10,20,30,40,50)
my_list=list(my_tuple)
my_list.sort()
my_tuple=tuple(my_list)
print("Sorted Tuple",my_tuple)

#--------------------------------------------------------------------------

#Q4 : count how many times an element appears in a tuple
def elementCount(my_tuple,element):
  print(element," appears",my_tuple.count(element),"times")

my_tuple=(10,20,10,30,30,20,20,10,50,60,50,10)
elementCount(my_tuple,10)
elementCount(my_tuple,50)

#--------------------------------------------------------------------------


Maximum number =  50
Minimum number =  10
Swapped Tuple (50, 20, 30, 40, 10)
Sorted Tuple (10, 20, 30, 40, 50)
10  appears 4 times
50  appears 2 times


# Dictionary

In [134]:
#Q1: Print student names who passes form dictionary
studentDictionary= {'Shadi':95,'Mohammad': 80,'Ali': 45,'Hassan': 32}
passedStudents=[]
for key,value in studentDictionary.items():
  if value >= 50:
    passedStudents.append(key)

print("Passed Students : ",passedStudents)

#--------------------------------------------------------------------------

#Q2: fnction to merge tow ditionaries in to one dictionary
dictionary1={'A':1,'B':2,'C':3}
dictionary2={'D':4,'E':5,'F':6}
dictionary1.update(dictionary2)
print("Merged Dictionary",dictionary1)

#--------------------------------------------------------------------------

#Q3: Get the key of the highest value in a dictionary without using max()
myDictionary={'A':1,'B':2,'C':3,'D':4}
highest_key = None
highest_value = 0

for key, value in myDictionary.items():
    if value > highest_value:
        highest_value = value
        highest_key = key

print('The highest key is : ',highest_key)

#------------------------------------------------------------------------------

#Q4:invert dictionary
myDictionary={'A':1,'B':2,'C':3,'D':4}
invertedDictionary={}
for key,value in myDictionary.items():
  invertedDictionary[value]=key
print("Inverted Dictionary",invertedDictionary)

#-------------------------------------------------------------------------------

#Q5: How many times each letter appears in a string using a dictionary
stingMessage = "hello shadi"
letter_counts = {}

for letter in stingMessage:
        if letter in letter_counts:
            letter_counts[letter] += 1
        else:
            letter_counts[letter] = 1

print('Letters counts',letter_counts)

#---------------------------------------------------------------------------

Passed Students :  ['Shadi', 'Mohammad']
Merged Dictionary {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6}
The highest key is :  D
Inverted Dictionary {1: 'A', 2: 'B', 3: 'C', 4: 'D'}
Letters counts {'h': 2, 'e': 1, 'l': 2, 'o': 1, ' ': 1, 's': 1, 'a': 1, 'd': 1, 'i': 1}


# Set

In [135]:
#Q1: intersection and union between tow set
set1={1,2,3,4,5}
set2={4,5,6,7,8}
intersection=set1.intersection(set2)
union=set1.union(set2)
print("Intersection : ",intersection)
print("Union : ", union)

#------------------------------------------------------------------

#Q2: remove duplicates from a list by converting it to set and back to a list
my_list=[1,2,3,4,5,6,7,8,9,1,2,3,]
my_set=set(my_list)
unique_list = list(my_set)
print("Unique List : ",unique_list)

#------------------------------------------------------------------

#Q3:Function to check if two sets are disjoint
def are_disjoint(set1, set2):
    if set1.isdisjoint(set2):
        return True
    else:
        return False

set1 = {1, 2, 3}
set2 = {4, 5, 6}
result = are_disjoint(set1, set2)
print("Are the two sets disjoint ? ",result)

#------------------------------------------------------------------

#Q4 : find the symmetric difference between two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
symmetric_difference = set1.symmetric_difference(set2)
print("Symmetric Difference : ",symmetric_difference)

#------------------------------------------------------------------


Intersection :  {4, 5}
Union :  {1, 2, 3, 4, 5, 6, 7, 8}
Unique List :  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Are the two sets disjoint ?  True
Symmetric Difference :  {1, 2, 3, 6, 7, 8}


# If Condition

In [136]:
#Q1: check if a number is positiv or negitive or zero
def check_number(number):
    if number > 0:
        print("The number ",number , " is positive.")
    elif number < 0:
        print("The number ",number , " is negative.")
    else:
        print("The number is zero.")

check_number(5)
check_number(-3)
check_number(0)

# ---------------------------------------------------------

#Q2: check if a given year is leap year
def is_leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        print(year, "is a leap year.")
    else:
        print(year, "is not a leap year.")


year = 2024
is_leap_year(year)
year = 2025
is_leap_year(year)

# ---------------------------------------------------------

#Q3 : check if  a character is a vowel or constant
def check_vowel_or_constant(char):
    vowels = "AEIOUaeiou"
    if char in vowels:
        print(char, "is a vowel.")
    else:
        print(char, "is a constant.")


char = 'E'
check_vowel_or_constant(char)
char = 'S'
check_vowel_or_constant(char)

# ---------------------------------------------------------



The number  5  is positive.
The number  -3  is negative.
The number is zero.
2024 is a leap year.
2025 is not a leap year.
E is a vowel.
S is a constant.


# While Loop

In [148]:
#Q1: print numbers from 1 to 100 but stops if the number is divisible by 17 by while loop
i = 1
while i <= 100:
    if i % 17 == 0:
        break
    print(i)
    i += 1

# ---------------------------------------------------------

#Q2: while loop to sums the numbers until the user enters -1
sum = 0
while True:
    number = int(input("Enter a number (enter -1 to stop): "))
    if number == -1:
        break
    sum += number
print("The sum of the numbers is:", sum)
#-----------------------------------------------------

#Q3: while loop to print odd numbers from 1 to 50
number=1
while number<=50:
  if number%2==1:
    print(number)
  number+=1

#-----------------------------------------------------



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
Enter a number (enter -1 to stop): 10
Enter a number (enter -1 to stop): -1
The sum of the numbers is: 10
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


# For Loop

In [139]:
#Q1: print multiplication table (from 1 to 10) for given number using a for loop
number=int(input("Enter a number: "))
for i in range(1,11):
  print(number,"x",i,"=",number*i)

#---------------------------------------------------------------------------

#Q2: Count how many vowels are in a given string
givenString=input("Enter a string: ")
vowels="aeiouAEIOU"
count=0
for char in givenString:
  if char in vowels:
    count+=1
print("The number of vowels in the string is: ",count)

#---------------------------------------------------------------------------

#Q3 : print element greater than 5 from a list by for loop
myList=[1,2,3,4,5,6,7,8,9,10]
for i in myList:
  if i>5:
    print(i)

#---------------------------------------------------------------------------


Enter a number: 10
10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100
Enter a string: jhgk
The number of vowels in the string is:  0
6
7
8
9
10


# Function

In [140]:
#Q1 function to get the factorial of number without using any libraries
def factorial(number):
    if number == 0 or n == 1:
        return 1
    else:
        return number * factorial(number - 1)

print(factorial(5))

#---------------------------------------------------------------------------

#Q2: function to check if  a string is a palindrome
def isPalindrome():
  givenString=input("Enter a string: ")
  if givenString==givenString[::-1]:
    print("The string is a palindrome")
  else:
    print("The string is not a palindrome")

isPalindrome()

#---------------------------------------------------------------------

#Q3: function to sequar all numbers of a list
def square(myList):
  squaredList=[]
  for n in myList:
    squaredList.append(n*n)
  return squaredList

myList=[1,2,3,4,5,]
mySquaredList=square(myList)
print(mySquaredList)

#---------------------------------------------------------------------


120
Enter a string: ugiu
The string is not a palindrome
[1, 4, 9, 16, 25]


# Recursion

In [141]:
#Q1: recursive function to find the nth fibonacci number
def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

print(fibonacci(10))

#---------------------------------------------------------------

#Q2: recursive function to compute the power of a number
def power(base, exponent):
    if exponent == 0:
        return 1
    elif exponent > 0:
        return base * power(base, exponent - 1)
    else:
        return

print(power(7,3))

#------------------------------------------------------------

#Q3: recursive function to compute the sum of a list of number
def listSum(myList):
    if len(myList) == 0:
        return 0
    else:
        return myList[0] + listSum(myList[1:])

myList = [1, 2, 3, 4, 5]
print(listSum(myList))

#------------------------------------------------------------


55
343
15


# Break and continue

In [142]:
#Q1: print numbers from 1 to 20 but skips multiple of 3
print('---- The numbers from 1 to 20 but skips multiple of 3 --------')
for i in range(1, 21):
    if i % 3 == 0:
        continue
    print(i)

#-------------------------------------------------------------------------

#Q2:  print numbers from 1 to 50 and breaks the loop if a number is divisible by 13 and 7
print('---- The numbers from 1 to 50 and breaks the loop if a number is divisible by 13 and 7 --------')
for i in range(1, 51):
    if i % 13 == 0 and i % 7 == 0 :
        break
    print(i)

#Q3: for loop that breaks when it find the first even number in a list
myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in myList:
    if i % 2 == 0:
        print("The first even number in a list is ",i)
        break

---- The numbers from 1 to 20 but skips multiple of 3 --------
1
2
4
5
7
8
10
11
13
14
16
17
19
20
---- The numbers from 1 to 50 and breaks the loop if a number is divisible by 13 and 7 --------
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
The first even number in a list is  2


# Lambda

In [143]:
#Q1: use a lambda function to sort a list of tuples based on the second element
my_list = [(1, 2), (3, 1), (2, 4), (4, 3)]
sorted_list = sorted(my_list, key=lambda x: x[1])
print(sorted_list)

#---------------------------------------------------------------------------

#Q2 : use a lambda function to return the sequar of number
sequaredNumber=lambda n: n*n
print(sequaredNumber(5))

#---------------------------------------------------------------------------

#Q3: use a lambda function to filter even numberfrom a list
NumberList=[1,2,3,4,5,6,7,8,9,10]
evenNumber=filter(lambda x: x%2==0,NumberList)
print("Even Number",list(evenNumber))

#---------------------------------------------------------------------------

[(3, 1), (1, 2), (4, 3), (2, 4)]
25
Even Number [2, 4, 6, 8, 10]


# Classes and OOP

In [149]:
#Q1: Create Car Class with attributes:
class car:
  brand=''
  model=''
  def displayCarInfo(self):
   print("Brand : ",self.brand)
   print("Model : ",self.model)

car1=car()
car1.brand='Toyota'
car1.model='Camry'
car1.displayCarInfo()

#Q2: creat a class with  a class method that return the number of objects created from the class
class person:
    count = 0

    def __init__(self):
        person.count += 1

    @classmethod
    def get_count(cls):
        return cls.count

person1 = person()
person2 = person()
person3 = person()

print("The number of objects created from the person class : ",person.get_count())

#---------------------------------------------------------------------------

#Q3: create parent class and child class that inherits from it and adds anew method
class parent:
  def parentMethod(self):
    print("This is parent method")

class child(parent):
  def childMethod(self):
    print("This is child method")


child1=child()
child1.childMethod()

#---------------------------------------------------------------------------

#Q4: write two classesDog and Cat that both have a method make_sound(), then call make_Sound() polymorphically
class Animal:
    def make_sound(self):
        print("The animal makes a sound.")
class Dog(Animal):
    def make_sound(self):
        print("Woof!")

class Cat(Animal):
    def make_sound(self):
        print("Meow!")

dog = Dog()
cat = Cat()

dog.make_sound()
cat.make_sound()

#---------------------------------------------------------------------------------

#Q5:creat an abstract class shape with an abstract method Area() and two child classes Rectangle and Circle
from abc import ABC,abstractmethod
class Shape(ABC):
  @abstractmethod
  def Area(self):
    pass

class Rectangle(Shape):
  def __init__(self,width,height):
    self.width=width
    self.height=height
  def Area(self):
    return self.width*self.height

class Circle(Shape):
  def __init__(self,radius):
    self.radius=radius
  def Area(self):
    return 3.14*self.radius*self.radius

rectangle=Rectangle(5,10)
circle=Circle(5)
print("Rectangle Area : ",rectangle.Area())
print("Circle Area : ",circle.Area())

#-------------------------------------------------

#Q6: create class with a private attribute and provide getter and setter method
class Person:
    def __init__(self, name, age):
        self._name = name
        self._age = age

    def get_name(self):
        return self._name

    def set_name(self, name):
        self._name = name

person1=Person("Ahmed",20)
print(person1.get_name())
person1.set_name("Ali")
print(person1.get_name())

Brand :  Toyota
Model :  Camry
The number of objects created from the person class :  3
This is child method
Woof!
Meow!
Rectangle Area :  50
Circle Area :  78.5
Ahmed
Ali


# JSON

In [145]:
#Q1 : Convert a Python dictionary into JSON string
import json
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
json_string = json.dumps(my_dict)
print("Json String ",json_string)

#--------------------------------------------------------------

#Q2: Read data from a JSON file and print it
json_string = '{"name": "John", "age": 30, "city": "New York"}'
data = json.loads(json_string)
print("My dictionary Data ",data)

#--------------------------------------------------------------

#Q3: write a python object (dictionary) into a JSON File
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
with open('my_file.json', 'w') as f:
    json.dump(my_dict, f)

#--------------------------------------------------------------


Json String  {"name": "John", "age": 30, "city": "New York"}
My dictionary Data  {'name': 'John', 'age': 30, 'city': 'New York'}


# NumBy

In [146]:
#Q1: create a 2D NumPy array of zeros
import numpy as np
array=np.array([[0,0,0],[0,0,0]])
print(array)
#-------------------------------------------------------------------------

#Q2 : creat 1D NumPy array of 10 random integers between and 100
randomIntegerArray=np.random.randint(100, size=10)
print(randomIntegerArray)
#-------------------------------------------------------------------------

#Q3: Find the mean,median and standard deviation of Numpy Array
array=np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean : ",np.mean(array))
print("Median : ",np.median(array))
print("Standard Deviation : ",np.std(array))

#---------------------------------------------------------------

#Q4: Reshap 1D array NumPy array to 2D array
array=np.array([1,2,3,4,5,6,7,8,9,10])
array=array.reshape(2,5)
print("Reshap 1D array to 2D array")
print(array)

#---------------------------------------------------------------

#Q5: Perform element-wise addition of two NumPy array
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
array=array1+array2
print("Element-wise addition of two NumPy array")
print(array)

#------------------------------------------------------------------

#Q6: Perform matrix multiplication between 2D NumPy array
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])
array=np.dot(array1,array2)
print("Matrix multiplication between 2D NumPy array")
print(array)

#-------------------------------------------------------------------------

#Q7: Find the maximum and minimum values in a NumPy array and their indices
array=np.array([1,2,3,4,5,6,7,8,9,10])
print("Maximum value in a NumPy array : ",np.max(array))
print("Minimum value in a NumPy array : ",np.min(array))
print("Maximum value index in a NumPy array : ",np.argmax(array))
print("Minimum value index in a NumPy array : ",np.argmin(array))

#-------------------------------------------------------------------------

#Q8: slice a NumPy array to get only the first 3 rows and 2 columns
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

sliced = arr[:3, :2]
print("The sliced array is : ")
print(sliced)


[[0 0 0]
 [0 0 0]]
[10 83 11 93 60 85 95 56 69 72]
Mean :  5.5
Median :  5.5
Standard Deviation :  2.8722813232690143
Reshap 1D array to 2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Element-wise addition of two NumPy array
[ 7  9 11 13 15]
Matrix multiplication between 2D NumPy array
[[19 22]
 [43 50]]
Maximum value in a NumPy array :  10
Minimum value in a NumPy array :  1
Maximum value index in a NumPy array :  9
Minimum value index in a NumPy array :  0
The sliced array is : 
[[ 1  2]
 [ 5  6]
 [ 9 10]]
